export default async function searchByTitle(title) {
  const storedMovies = {
    'titanic': { "Title": "Titanic", "Year": "1997", "Rated": "PG-13", "Released": "19 Dec 1997", "Runtime": "194 min", "Genre": "Drama, Romance", "Director": "James Cameron", "Writer": "James Cameron", "Actors": "Leonardo DiCaprio, Kate Winslet, Billy Zane, Kathy Bates", "Plot": "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.", "Language": "English, Swedish", "Country": "USA", "Awards": "Won 11 Oscars. Another 111 wins & 77 nominations.", "Poster": "https://ia.media-imdb.com/images/M/MV5BMDdmZGU3NDQtY2E5My00ZTliLWIzOTUtMTY4ZGI1YjdiNjk3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "7.8/10" }, { "Source": "Rotten Tomatoes", "Value": "88%" }, { "Source": "Metacritic", "Value": "75/100" }], "Metascore": "75", "imdbRating": "7.8", "imdbVotes": "893,280", "imdbID": "tt0120338", "Type": "movie", "DVD": "10 Sep 2012", "BoxOffice": "N/A", "Production": "Paramount Pictures", "Website": "http://www.titanicmovie.com/", "Response": "True" },
    'xxx': { "Title": "xXx", "Year": "2002", "Rated": "PG-13", "Released": "09 Aug 2002", "Runtime": "124 min", "Genre": "Action, Adventure, Thriller", "Director": "Rob Cohen", "Writer": "Rich Wilkes", "Actors": "Vin Diesel, Asia Argento, Marton Csokas, Samuel L. Jackson", "Plot": "An extreme sports athlete, Xander Cage, is recruited by the government on a special mission.", "Language": "English, German, Spanish, Russian, Czech", "Country": "USA", "Awards": "4 wins & 14 nominations.", "Poster": "https://ia.media-imdb.com/images/M/MV5BNzZjZmM1ZDctNDhlZi00Mzk1LWFjNWItYzIxNGY2OWYzYjJmXkEyXkFqcGdeQXVyNjQ2MjQ5NzM@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "5.9/10" }, { "Source": "Rotten Tomatoes", "Value": "48%" }, { "Source": "Metacritic", "Value": "48/100" }], "Metascore": "48", "imdbRating": "5.9", "imdbVotes": "158,997", "imdbID": "tt0295701", "Type": "movie", "DVD": "31 Dec 2002", "BoxOffice": "$141,134,092", "Production": "Columbia Pictures", "Website": "http://www.sonypictures.com/movies/triplex/", "Response": "True" }
  };

  const normalizedTitle = title.toLowercase();

  return storedMovies[normalizedTitle] || null;
}
