export default async function searchByTitle(title) {
  const storedMovies = {
    'titanic': { "Title": "Titanic", "Year": "1997", "Rated": "PG-13", "Released": "19 Dec 1997", "Runtime": "194 min", "Genre": "Drama, Romance", "Director": "James Cameron", "Writer": "James Cameron", "Actors": "Leonardo DiCaprio, Kate Winslet, Billy Zane, Kathy Bates", "Plot": "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.", "Language": "English, Swedish", "Country": "USA", "Awards": "Won 11 Oscars. Another 111 wins & 77 nominations.", "Poster": "https://ia.media-imdb.com/images/M/MV5BMDdmZGU3NDQtY2E5My00ZTliLWIzOTUtMTY4ZGI1YjdiNjk3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "7.8/10" }, { "Source": "Rotten Tomatoes", "Value": "88%" }, { "Source": "Metacritic", "Value": "75/100" }], "Metascore": "75", "imdbRating": "7.8", "imdbVotes": "893,280", "imdbID": "tt0120338", "Type": "movie", "DVD": "10 Sep 2012", "BoxOffice": "N/A", "Production": "Paramount Pictures", "Website": "http://www.titanicmovie.com/", "Response": "True" },
    'xxx': { "Title": "xXx", "Year": "2002", "Rated": "PG-13", "Released": "09 Aug 2002", "Runtime": "124 min", "Genre": "Action, Adventure, Thriller", "Director": "Rob Cohen", "Writer": "Rich Wilkes", "Actors": "Vin Diesel, Asia Argento, Marton Csokas, Samuel L. Jackson", "Plot": "An extreme sports athlete, Xander Cage, is recruited by the government on a special mission.", "Language": "English, German, Spanish, Russian, Czech", "Country": "USA", "Awards": "4 wins & 14 nominations.", "Poster": "https://ia.media-imdb.com/images/M/MV5BNzZjZmM1ZDctNDhlZi00Mzk1LWFjNWItYzIxNGY2OWYzYjJmXkEyXkFqcGdeQXVyNjQ2MjQ5NzM@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "5.9/10" }, { "Source": "Rotten Tomatoes", "Value": "48%" }, { "Source": "Metacritic", "Value": "48/100" }], "Metascore": "48", "imdbRating": "5.9", "imdbVotes": "158,997", "imdbID": "tt0295701", "Type": "movie", "DVD": "31 Dec 2002", "BoxOffice": "$141,134,092", "Production": "Columbia Pictures", "Website": "http://www.sonypictures.com/movies/triplex/", "Response": "True" },
    'the green mile': { "Title": "The Green Mile", "Year": "1999", "Rated": "R", "Released": "10 Dec 1999", "Runtime": "189 min", "Genre": "Crime, Drama, Fantasy", "Director": "Frank Darabont", "Writer": "Stephen King (novel), Frank Darabont (screenplay)", "Actors": "Tom Hanks, David Morse, Michael Clarke Duncan, Bonnie Hunt", "Plot": "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.", "Language": "English, French", "Country": "USA", "Awards": "Nominated for 4 Oscars. Another 15 wins & 32 nominations.", "Poster": "https://ia.media-imdb.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "8.5/10" }, { "Source": "Rotten Tomatoes", "Value": "80%" }, { "Source": "Metacritic", "Value": "61/100" }], "Metascore": "61", "imdbRating": "8.5", "imdbVotes": "916,580", "imdbID": "tt0120689", "Type": "movie", "DVD": "13 Jun 2000", "BoxOffice": "N/A", "Production": "Warner Bros. Pictures", "Website": "http://www.thegreenmile.com", "Response": "True" },
    'shrek': { "Title": "Shrek", "Year": "2001", "Rated": "PG", "Released": "18 May 2001", "Runtime": "90 min", "Genre": "Animation, Adventure, Comedy", "Director": "Andrew Adamson, Vicky Jenson", "Writer": "William Steig (based upon the book by), Ted Elliott, Terry Rossio, Joe Stillman, Roger S.H. Schulman, Cody Cameron (additional dialogue), Chris Miller (additional dialogue), Conrad Vernon (additional dialogue)", "Actors": "Mike Myers, Eddie Murphy, Cameron Diaz, John Lithgow", "Plot": "After his swamp is filled with magical creatures, Shrek agrees to rescue Princess Fiona for a villainous lord in order to get his land back.", "Language": "English", "Country": "USA", "Awards": "Won 1 Oscar. Another 36 wins & 60 nominations.", "Poster": "https://ia.media-imdb.com/images/M/MV5BOGZhM2FhNTItODAzNi00YjA0LWEyN2UtNjJlYWQzYzU1MDg5L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "7.9/10" }, { "Source": "Rotten Tomatoes", "Value": "88%" }, { "Source": "Metacritic", "Value": "84/100" }], "Metascore": "84", "imdbRating": "7.9", "imdbVotes": "525,022", "imdbID": "tt0126029", "Type": "movie", "DVD": "02 Nov 2001", "BoxOffice": "$266,982,666", "Production": "Dreamworks", "Website": "http://www.shrek.com/", "Response": "True" },
    'b': { "Title": "B", "Year": "2015", "Rated": "N/A", "Released": "18 Sep 2015", "Runtime": "80 min", "Genre": "Crime, Drama", "Director": "David Ilundain", "Writer": "Jordi Casanovas (play), David Ilundain (adaptation)", "Actors": "Pedro Casablanc, Manolo Solo, Pedro Civera, Eduardo Recabarren", "Plot": "July 15, 2013 Luis Barcenas - Old party treasurer was transferred from prison to National Court to testify. Previously, he had denied everything. Today he will tell the truth.", "Language": "Spanish", "Country": "Spain", "Awards": "5 wins & 8 nominations.", "Poster": "https://ia.media-imdb.com/images/M/MV5BZDhlZmRlNmMtYmMyYy00Zjg0LWI0ZmQtYzNiNWM5YTU4YTI3XkEyXkFqcGdeQXVyNjQ0NjY3MDY@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "6.9/10" }], "Metascore": "N/A", "imdbRating": "6.9", "imdbVotes": "403", "imdbID": "tt4679438", "Type": "movie", "DVD": "N/A", "BoxOffice": "N/A", "Production": "N/A", "Website": "N/A", "Response": "True" }
  };

  const normalizedTitle = (title && title.toLowerCase()) || '';

  return storedMovies[normalizedTitle] || null;
}
